// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kuaxylxgyjygfmixkmhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1YXh5bHhneWp5Z2ZtaXhrbWhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMTE2NjgsImV4cCI6MjA2NTY4NzY2OH0.0gZh2Pz2kA-BUV2eD_TrYESp2wbYu0Eo0NfaCz4I6Ck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);